### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by zeinghra** [th3unkn0n/facebash-termux#5]

**Comment by zeinghra** [comment]
S

**Comment by zeinghra** [comment]
Sorry i don't know how to close this

**Comment by zeinghra** [comment]
![Screenshot_20210422-194034](https://user-images.githubusercontent.com/81908720/115752292-798c0a80-a389-11eb-9569-77c19c05ccff.png)
Thats the problem
./facebash.sh does not work

**Comment by th3unkn0n** [comment]
cd facebash-termux
./facebash.sh

**Comment by Mann-Joshi** [comment]
Write bash facebash.sh
